selectList_maplestory = [
"10주년 마블 - Tenth_Board",
"11주년 축제장 - Happy_Time",
"12주년 몬스터 보물 마을 - Monster_World",
"12주년 몬스터 보물창고 멀티 - Tresure_Game_Multi",
"12주년 몬스터 보물창고 싱글 - Tresure_Game_Single",
"14주년 행성비타 - mapleGalaxy",
"14주년 행성쁘띠 - LittleMaplePlanet",
"15주년 15번가 - Welcome_to_the_15th_Street",
"15주년 클럽 V - Maplestory_Mashup",
"16주년 구버전 로그인화면 8Bit - Start_the_Adventure_(NEWTRO Ver.)",
"16주년 꿈의 도시 레헬른 8Bit - Lachln_the_Illusion_City_(NEWTRO Ver.)",
"16주년 뉴트로 디스코 - Newtro_Disco",
"16주년 뉴트로 킹덤(로비) - Newtro_Kingdom",
"16주년 루디브리엄 8Bit - The_Fantastic_Thinking_(NEWTRO Ver.)",
"16주년 리스항구 8Bit - Above_The_Treetops_(NEWTRO Ver.)",
"16주년 마가티아 8Bit - Dispute_(NEWTRO Ver.)",
"16주년 망각의 호수 8Bit - The_Lake_of_Oblivion_(NEWTRO Ver.)",
"16주년 무릉 8Bit - Mureung_Hill_(NEWTRO Ver.)",
"16주년 아리안트 8Bit - Ariant_(NEWTRO Ver.)",
"16주년 아리안트 투기대회 8Bit - Arab_Pirate_(NEWTRO Ver.)",
"16주년 에델슈타인 8Bit - Edelstein_City_(NEWTRO Ver.)",
"16주년 에우렐 8Bit - Wind_and_Flower_(NEWTRO Ver.)",
"16주년 차원의 도서관 8Bit - The_Dimension_Library_(NEWTRO Ver.)",
"16주년 츄츄아일랜드 8Bit - Expedition_to_ChewChew_Island_(NEWTRO Ver.)",
"16주년 커닝시티 8Bit - BadGuys_(NEWTRO Ver.)",
"16주년 플로리나 비치 8Bit - Florina_Beach(Beachway)_(NEWTRO Ver.)",
"16주년 헤네시스 8Bit - Floral_Life_(NEWTRO Ver.)",
"17주년 호텔 메이플 - 17th_Anniversary_Hotel_Maple",
"2009 마녀의 탑 - WichTower",
"2011 돌고래 섬 낮 - dolphin_noon",
"2011 돌고래 섬 밤 - dolphin_night",
"2012 메이플 스쿨 - Maple_High_School",
"2012 할로윈 레이싱 - Halloween_Racing",
"2012 할로윈 메인홀 - Halloween_Main_Hall",
"2012 할로윈 파티홀 - Halloween_Party",
"2013 미니게임 스테이션Mini_Game_Station",
"2013 서바이벌 미니게임 - The_Rush",
"2017 해변의 무법자 - Outlaw of the Lonely Island",
"2018 할로윈 메인화면 - Club_Halloween",
"2021년 평범한 마을 - 2021year",
"2099년 한밤의 항만 - 2099year",
"2215년 폭격을 맞은 도심 - 2215year",
"2230년 위험한 타워 - 2230year",
"2503년 천공전함 헤르메스 - 2503year",
"8주년 메인화면 - Title_8th",
"8주년 오프닝 테마 - Smile_Love_U",
"Act.2 에반 각성 - Anthem_for_Heroes",
"Act.2 오르비스 상공 - Endless_Journey",
"Act.3 마족 침공 - Time_is_Gold",
"Act.3 알리샤, 데미안 - The_Devil_is_Coming",
"Act.3 코스믹 뮤지엄 - Jazz_for_Dr.Lim",
"AWAKE 티저 - Awake_Teaser",
"ep.1 오로라 대신전 - The_Aurora",
"ep.1 폭풍우치는 숲 - The_Stormy_Forest",
"ep.4 설원의 음유시인 연주곡 - noname",
"ep.4 설원의 음유시인1 - ForgottenNames",
"ep.4 설원의 음유시인2 - Nowhere",
"ep.4 설원의 음유시인3 - WayBackHome",
"ep.5 그림자 연금술사 - EveningPrimrose",
"ep.6 샤레니안의 기사 1 - My_Prince_My_Kingdom",
"ep.6 샤레니안의 기사 2 - The_Knight_of_Sharenian",
"ep.6 샤레니안의 기사 3 - White_Night",
"Mr.해저드의 구역 - MrHazard",
"M타워 최상층 - T_Bomb",
"PC방(커닝시티) - Play_With_Me",
"RISE 살롱 - Salon_RISE",
"UFO 내부 - DancesWithAliens",
"각성의 산 - Awakening_mountain",
"갓 오브 컨트롤 - God_of_Control_Stage",
"갓 오브 컨트롤 로비 - God_of_Control_Lobby",
"개그씬 - Smile_Zero",
"개미굴 - Ancient_Move",
"거울빛에 물든 바다 - ConteminatedSea",
"거울빛에 물든 바다(구버전) - ConteminatedSea",
"거울세계 루디브리엄 - Fantastic_Thinking_in_Mirror",
"거울세계 리프레 - Leafre_in_Mirror",
"거울세계 마가티아 - Dispute_in_Mirror",
"거울세계 무릉도원 - Mureung_Hill_in_Mirror",
"거울세계 시간의 신전 - Time_Temple_in_Mirror",
"거울세계 아리안트 - Ariant_in_Mirror",
"거울세계 에델슈타인 - Edelstein_City_in_Mirror",
"거울세계 컨트롤룸 - Red_Room",
"거울세계 컨트롤룸 - Red_Room(구버전)",
"거울세계 헤네시스 - Floral_Life_in_Mirror",
"거울에 비친 빛의 신전 - TempleInTheMirror",
"거울에 비친 빛의 신전(구버전) - TempleInTheMirror",
"검은 바이킹의 방 - Viking_Skipper",
"검은 분노 - Black_Fury",
"검의 무덤 - Graveyard_of_Sword",
"겔리메르의 연구소 - Gelimer_Lab",
"겨울왕국 메인화면 - Title_Frozen",
"격납고 - For_the_Glory",
"고대도시 아스완 - Rusty_Throne",
"고스트파크 - Welcome_to_the_Creepy_Ghost_Park",
"고스트파크 고스트하우스 - Dancing_with_Ghosts",
"고통의 미궁 내부 - Secret_Labyrinth",
"고통의 미궁 중심부 - Eternal_Swamp",
"고통의 미궁 최심부 - Heart_of_Suffering",
"공격당한 메이플 아일랜드 - WoundedLeaf",
"공허의 눈, 거대 괴수 - Ferocious_Battlefield",
"공허의 파도 - Wave_of_Emptiness",
"구름너머 - OverTheClouds",
"구름너머(퀘스트중) - OverTheClouds_RhythmicVer",
"구버전 메인화면 - Title",
"그림자 기사단 - Shadow_Knight",
"그림자 신전 - Shadow_Temple",
"그림자가 춤추는 곳, 폐쇄 구역 - BlackDungeon",
"근두운 (호영 튜토리얼) - Riding_on_the_clouds",
"근본중당 내부, 작은 사당 내부 - Hieijan_Nohime",
"글로리온 전초기지 - Glory_Base",
"금지된 절벽 - This_too_shall_pass_away",
"기계무덤 - Junk_Yard",
"기계무덤 헤이븐 - Haven_Theme",
"기사단의 요새 - Knights_Stronghold",
"기타 연주 미니게임 - The_Beast",
"깊은 거울, 보스 윌 페이즈2 - MirrorCage",
"깊은 거울, 보스 윌 페이즈2(구버전) - MirrorCage",
"까막산 - Dark_Mountain",
"꽃보다 비올레타 - Flower Violeta",
"꿈 속의 숲 (에반 튜토리얼) - Dragon_Dream",
"꿈의 도시 레헬른 - Lachln_the_Illusion_City",
"끝없이 추락하는 심해 - Sinking_Things",
"끝에 가까운 곳 - Subterminal_Point",
"끝이 아닌 새로운 시작 - New_Beginning_Not_The_End",
"나이트워커 하이퍼 스킬 - Dominion",
"네오 캐슬 - Neo_Castle",
"네트의 피라미드 - Net's_Piramid",
"노틸러스 내부 - in_Nautilus",
"노틸러스 선착장,코코섬 - Nautilus",
"당주의 방 - Kecon",
"대난투 배틀 스퀘어 - Battle_Entrance",
"대난투 사자왕의 성 탑루 팀매치 - Battle_BGM_Type_A",
"대난투 엘리쟈의 정원 팀매치 - Battle_BGM_Type_C",
"대난투 팀 매치,서바이벌 - Battle_BGM_Type_B",
"대난투 핑크빈의 음악 감상 서바이벌 - Battle_BGM_Type_D",
"대만 서문정 - Yo_Taipei",
"대만 야시장 - Night_Market",
"대만 야시장 필드 - Night_Field",
"더스트 존 - Battlefield",
"데몬 튜토리얼 (결전) - Decisive_Battle",
"데몬 튜토리얼 - Despair_On_Devil",
"데미안 1페이즈 - Demian",
"데미안 2페이즈 -  Demian True",
"데미안 각성전 - Demian Spine",
"데미안 사망 - Pain to Hope",
"데미안과 아이들 등장 - The_Beast_2",
"도깨비 야시장 - Goblin_Market",
"도심지 탈환전 - Helisium_War_Cry",
"독안개의 숲 - PoisonForest",
"동굴 깊은 곳 - Deep_Cave",
"동쪽 바다 - Shining_Sea",
"두꺼비 영주 - CastleBoss",
"뒤틀린 시간의 길 1,2 - Fairy_Tale",
"뒤틀린 시간의 길 3,4 - Fairy_Tale_(diff_vers)",
"뒤틀린 회랑 - Bizarre_Tales",
"드라이 로드 - Low_Grade_Ore",
"드라이 로드(구버전) - Low_Grade_Ore",
"드래곤 라이더 보스전 - Dragon_Rider",
"떠오르는 태양 - Rising_Sun",
"라니아의 집 - Peaceful_Woods",
"레벤 광산 - Power_Station",
"레지스탕스 기지 - Underground_Place",
"로비 - Venture_into_the_Unknown",
"로스웰 초원 - Let's_Hunt_Aliens",
"루디브리엄 - Fantastic_Thinking",
"루디브리엄 Jazz - The_Fantastic_Thinking_(JAZZ Ver.)",
"루디브리엄행 항해중 - Flying_in_a_Blue_Dream",
"루미너스 빛어둠 선택 - Flood",
"루미너스 튜토리얼 - Dark_Mage",
"루미너스 튜토리얼 - Final_Fight",
"루엔의 집 - Luens_House",
"루타비스 - Yggdrasil_Prayer",
"리스토니아 - Romantic_Sunset",
"리스항구 - Above_the_Treetops",
"리에나 해협 필드 - Glacier_Adventure",
"리에나 해협 항해중 - Sailing",
"리엔 - Rien_Village",
"리엔 수련장 - Bamboo_Gym",
"리엔 수정동굴 - Crystal_Cave",
"리엔 필드 - Snow_Drop",
"리프레 - Leafre",
"리프레 동,서쪽 숲 - Minar's_Dream",
"마가티아 - Dispute",
"마법 도서관(구버전) - Elf_Wood",
"마스터의 복수 - Dragon_Tiger_Dungeon",
"마스테리아의 제단 - Crimsonwood_Keep_Interior",
"마스테리아의 제단1 - Courtyard",
"마스테리아의 제단2 - PartyQuest_GL",
"마이스터 빌 - Profession",
"망각의 길 - Forgetfulness",
"망각의 호수 - Lake_of_Oblivion",
"매그너스 - The_Final_War",
"매그너스의 수호자 - Trinity_Force",
"메이플 아일랜드 - Maple_Leaf",
"메이플 운동회 - FunnyRabbit",
"메이플 운동회 2단계 - FunnyRabbitFaster",
"메인테마 - Heroes_of_Maple_Theme",
"모험가 애니메이션 인트로 - Go_Fight!_Show_Your_Energy! -",
"몬스터 파크 - MonsterPark",
"몬스터 파크 숨겨진 보물창고 - MP_Bonus_Map",
"몬스터라이프 농장1 - It's_Monster_Life",
"몬스터라이프 농장2 - It's_Monster_Life_2",
"몬스터라이프 몬스터 방출 - journey",
"몬스터라이프 상점 - specialtyStore",
"몬스터라이프 율리앙의 집 - scholarsLibrary",
"몬스터라이프 특별한 상점 - specialtyStoreRemix",
"몽환의 숲;루시드 1페이즈 - Weird_Froest_In_The_Girls_Dream",
"무너지는 시계탑;루시드 2페이즈 - Broken_Dream",
"무릉 - Mureung_Hill",
"무릉도장1 - Mureung_School_1",
"무릉도장2 - Mureung_School_2",
"무릉도장3 - Mureung_School_3",
"무릉도장4 - Mureung_School_4",
"미개통 구간 - Under_Subway",
"미나르숲 탐사본부,필드 - The_Raiders",
"미남 법사의 사원 - Creepy_Temple",
"미래의 문 - Time_Gate",
"미지의 안개 - Strange_Fog",
"바스라지는 빛, 보스 윌 페이즈3 - BloodCage",
"바스라지는 빛, 보스 윌 페이즈3(구버전) - BloodCage",
"바이킹의 비행선 - Viking_Ship",
"반 레온 - LionHeart",
"반반 - Time_Chaos",
"배틀 몬스터 - rock`nBattle",
"배틀 호라이즌 - Battle_Horizon",
"백초마을 - White_Herb",
"버려진 사원,라바나 - Gold_Temple_Dungeon",
"버려진 탑 (탑의 암흑) - Dark_Shadow",
"버려진 탑 - Fantasia",
"버섯의 성 - Mushroom_Castle",
"버섯의 성 성벽 - War_Mush_Castle",
"벚꽃성 내부 - CastleInside",
"벚꽃성 외부 - CastleOutSide",
"베르딜 - VerdelTown",
"베르딜 필드 - VerdelField",
"베리타스 - In_All_Verity",
"베릴 테마 - Pulse_Resonance",
"베이스 캠프, 생명이 시작되는 곳 - SoupOfLife",
"베이스 캠프, 생명이 시작되는 곳(구버전) - SoupofLife",
"벨룸 - Abyss_Cave",
"별이 삼켜진 심해 - Whale_Belly",
"보더리스 - Borderless",
"보스 - Amusing_Story_in_the_Fairy_Tale",
"보스 카웅 - VacuumCleaner",
"불사의 고르곤 - Immortal_gorgons",
"불타는 라니아의 집 - Burning_Woods",
"불타는 세르니움 광장 - Burning_City",
"불타버린 땅 - Highland_Star",
"붉은 달 - Red_Moon",
"블랙윙 테마 - Black_Wing",
"블랙헤븐 - Black_Heaven_Theme",
"블랙헤븐 갑판 위 - Battle_on_the_Deck",
"블랙헤븐 갑판 전투 - Hero_Comes",
"블랙헤븐 내부 - Big_Machine",
"블랙헤븐 내부 - Big_Machine_Mission",
"블랙헤븐 에필로그 - Heaven_Again",
"블랙헤븐 에필로그(떠날때) - HeavenAgain_reprise",
"블랙헤븐 엔딩 크레딧 - Promise_of_Heaven",
"블랙헤븐 엔딩 크레딧 MR - Promise_of_Heaven_(Vocaless_ver)",
"블러디 퀸 - Queens_Palace",
"비 오는 뾰족귀 여우마을 - Sad_Fox_Village",
"비극의 성벽 - The_Walls_of_Tragedy",
"비밀작전 - Secret_Mission",
"비화원 - Secret_Flower",
"빛이 마지막으로 닿는 곳 - Where_Stars_Rest",
"빛이 마지막으로 닿는 곳(구버전) - Where_Stars_Rest",
"빨간코 해적단 소굴 - Pirate",
"뾰족귀 여우마을 - Fox_Village",
"사막던전 - VerdelDungeon",
"사상의 경계, 영웅집결 퀘스트 - War_Cloud",
"사자왕의 성 - Blizzard_Castle",
"사자왕의 성 탑루,장미정원 - Crimson_Tower",
"산호 숲으로 가는 길 - SwampOfMemoryMoras",
"새비지 터미널 - SavageTerminal",
"새비지 터미널 암시장 - HuntingGround",
"생명의 동굴 - Cave_of_Hontale",
"생명의 초월자 - Overload_of_Life",
"서울 시내 (야간) - Unknown_Part_of_City",
"서울 시내 (주간) - Skyscraper",
"서쪽 바다 - Blue_World",
"선셋로드 - Sunset_Desert",
"선유산 기슭 (호영 튜토리얼) - SeonYuSan",
"설귀도 - Through_the_Blizzard",
"설귀도 마족군대 - Army_of_Fears_Theme",
"설치)250,275레벨 기념 의자 - maxLevelChair",
"성검이 보관된 곳 - Sanctuary_of_Mitra",
"성스러운 전쟁 - Holy_War",
"세계가 끝나는 곳 - The_Worlds_End",
"세계의 눈물 - Tears_of_the_World",
"세레니티 - Serenity",
"세르니움 광장 - The_Holy_Land",
"세르니움 전장 - Battle_of_Cernium",
"셀라스 퀘스트 중 - Goodbye_My_Friends",
"소멸의 화염지대 - Volcanic_Zone_of_Extinction",
"소비)러블리 파티베어 - Lovely_Party_Bear",
"소비)축하 오르골 - Congratulation",
"수상한,변절한 기지 - Base_of_Betrayers",
"수행자의 숲 - Gold_Temple_Field",
"쉼터 - The_Bottom_of_the_Sea",
"스우 1페이즈 - Gravity_Core",
"스우 2페이즈 - Gravity_Lord",
"스우 3페이즈 - Gravity_Lord_Rise",
"스타 윷놀이 - YUT_YUT_YUT",
"스타플래닛 게임대기 - Star_Planet_Game_Field",
"스타플래닛 메인 - Star_Planet_Main_Event",
"스타플래닛 서버 입장대기실 - Star_Planet_Wait_Field",
"스타플래닛 월드 미니게임 - Star_Planet_World_Event",
"스타플래닛 인트로 - Invitation_Star_Planet",
"슬리피우드 - Sleepy_Wood",
"슬픈 장면 - Nasty_Liar",
"시간의 갈림길 - Wherever_You_are",
"시간의 신전 - Time_Temple",
"시그너스 기사단 테마 - Cygnus",
"시그너스의 전당 - Cygnus_Garden",
"시그너스의 전당 Jazz - Cygnus_Garden_(JAZZ Ver.)",
"시작과 끝이 경계 - World_Horizon",
"신버전 메인화면 - Title",
"신버전 메인화면 Jazz - Title_(JAZZ Ver.)",
"신수국제학교 - School_Life",
"신수국제학교 구관 - Hollow_Attack",
"신수국제학교 도심 - Urban_Street",
"신의 사도 - Apostles",
"신전 깊은 곳 - Dusk_of_God",
"심해 - Deep_See",
"심해 동굴 - Aqua_Cave",
"싸워라!전설의 귀환 - Virtual_Arena",
"아델의 맹세 - Adele's_Oath",
"아랫마을 - Down_Town",
"아르카나 - TheTuneOfAzureLight",
"아르카나 동굴 - TheTuneOfAzureLight2",
"아르카나 퀘스트테마 - ArcanaBoss",
"아리안트 - Ariant",
"아리안트 Jazz - Ariant_(JAZZ Ver.)",
"아리안트 투기대회 - Fight_Sand",
"아리안트 필드 - Hot_Desert",
"아리안트 필드(구버전) - Hot_Desert",
"아쉴롬 - Asylum",
"아쉴롬2 - AsylumPiano",
"아스완 해방전 - In_Wartime",
"아카이럼 - Altar_of_Akayrum",
"아쿠아리움 - Aquarium",
"아크 과거회상 (추억) - Memory",
"아프리엔 사망, 타락한 세계수 - Pain_and_Sorrow",
"악몽의 시계탑 - Clock_Tower_Of_Nightmare",
"안개바다의 유령선 보스전 - Ghost_Ship",
"안식의 동굴 - Cave_of_Rest",
"알려지지 않은 폐광 - Mine_Quest",
"알리샤르 - They_Menacing_You",
"암벽거인의 몸 - The_Living_Mountain",
"암벽거인의 심장 - The_Colossal_Heart",
"야외연극무대 - Mole_King_Rises",
"얌얌 빌리지,머쉬버드 숲 - Mushbud_Forest",
"양떼목장 이벤트 - WolfAndSheep",
"어둠에 잠긴 라니아의 집 - Dark_Woods",
"어둠에 잠긴 엘리니아 - Speak_in_the_Void",
"어둠의 신전 - Temple_of_Darkness",
"어둠의 옥좌 - Throne_of_Darkness",
"어드벤처 아일랜드 - Adventure_Island",
"얼어붙은 에우렐 (메르세데스 튜토리얼) - Flower_in_Blue",
"에델슈타인 - Edelstein_City",
"에레고스 - Eregos",
"에레브 - Queens_Garden",
"에레브 사냥터 - Raindrop_Flower",
"에레브 사냥터 Jazz - Raindrop_Flower_(JAZZ Ver.)",
"에레브 연무장 - Drill_Hall",
"에오스탑 외부 - High_Enough",
"에오스탑,헬리오스탑 - Funny_Time_Maker",
"에우렐 - Wind_and_Flower",
"에우렐 엘프의 오르골 - Sound_of_Elf",
"에인헤랴르를 위해 - For_Einherjar",
"에피네아 - QueensHideout",
"엔딩 크레딧 -  Travelers",
"엔젤릭버스터 스포트라이트 - 5thSpotLightFlyAway",
"엔젤릭버스터의 방 - Angel's_Room",
"엘나스 - Snowy_Village",
"엘나스 필드 - Warm_Regard",
"엘로딘 필드 - Secret_Elodin",
"엘리니아 - When_the_Morning_Comes",
"엘리니아 나무던전 - Missing_You",
"엘리니아 필드 - Moonlight_Shadow",
"엘리트보스 보상 - HappyTimeShort",
"엘리트보스 출현 - Royal_Guard",
"엘린 숲 - ElinForest",
"엘린 숲 동굴 - ElinCave",
"여신의 탑 - Tower_of_Goddess",
"연날리기 - Kite_BGM",
"연합회의장 - Heroes_of_Maple_Theme(Piano_ver)",
"영웅 활약 - Showtime!",
"오늘의 운세 - TodaysFortune",
"오르비스 - Shinin'_Harbor",
"오르비스탑 - Come_with_Me",
"오르비스행 항해중 (크림슨발록 출현) - Arab_Pirate",
"오르비스행 항해중 - Upon_the_Sky",
"오르카의 내면세계 - Rabbits_Dream",
"오염된 하수구 - Los_Gurugers",
"요정학원 엘리넬 - The_Fairy_Academy",
"요정학원 엘리넬 필드 - The_Fairy_Forest",
"욕망의 제단, 진 힐라 - Depth_of_Pain",
"용암 동굴 - Hell_Gate",
"용의 숲 - Dragon_Load",
"용의 협곡 - Dragon_Nest",
"우르스 입장 대기 - She_Sells_a_Lucky_Thing",
"운명의 날 - Doomsday_FULL",
"운명의 날 - Doomsday_LOOP",
"웨딩빌리지 - wedding",
"웨딩빌리지 - weddingDance",
"웨딩빌리지 웨딩홀 - Amoria",
"유적 발굴지 - Ancient_Remain",
"유적 발굴지 군영 - Ruin_Castle",
"유적 수호자의 길, 파르템 유적 - The_Partem_Ruins",
"유적 진입로 - Timeless_Beholder",
"은월 튜토리얼 - Decision",
"이볼빙 시스템 내부 - EvolvingWorld",
"일리야드 들판 - Illiyard_Moor",
"일리움 전직테마1 - DeathOfAsylumChoirExtended",
"일리움 전직테마2 - IlliumRebirth",
"일리움 테마1 - AsylumAmbience",
"일리움 테마2 - AsylumAmbiencePiano",
"일리움 튜토리얼 - AsylumPiano",
"일본 버섯신사 - Feeling",
"일본 월하죽림 - Bizarre_Forest",
"잊혀진 시간의 길 1,2 - Timeless",
"잊혀진 시간의 길 3,4 - Timeless_B",
"잊혀진 회랑 - The_Way_Grotesque",
"자쿰 (구버전) -  Final_Fight",
"자쿰 - Welcome_to_the_Hell",
"장난감 공장 - Waltz_for_Work",
"저주받은 신전 - Evil_Eyes",
"저택 - Masked_Heart",
"전사의 성전(구버전) - Where_the_Barlog_From",
"전초기지 - Outpost",
"제논 튜토리얼 - From_Under_to_Upper",
"제논 튜토리얼 - Underside",
"제논의 기억 - The_Photo",
"제로의 신전 - Be_Born_Zero",
"존재하지 않는 공간 - Lost_Space",
"죽은 나무의 숲 - Wolf_Wood",
"중국 상해 와이탄 - Go_Shanghai",
"중국 상해 와이탄(구버전) - Go_Shanghai",
"중국 상해 외곽 - Shanghai_Field",
"지구방위본부 - Let's_March",
"지구방위본부 퀘스트(린이의 결심) - GoGoRangers!",
"지구방위본부(구버전) - Let's_March",
"지상낙원 골드비치 - Gold_Beach",
"지상열차,M타워 - Reverse_City_2",
"지하 통로 - Where_the_Secret_Lies",
"지하선로 - Reverse_City",
"지하수로 - Water_Way",
"차원의 도서관 - DimensionLibrary",
"차원의 틈 - Crack_of_Dimension",
"천상의 크리세 - Krease_Agit",
"청운골 - CheongUn",
"초창기 메인화면 - The_Third_Fight",
"추억의 길 - Remembrance",
"출동! 메소레인저 시즌1_1 -rhythmBgm1",
"출동! 메소레인저 시즌1_2 - rhythmBgm2",
"출동! 메소레인저 시즌3_1 - Santa_Beats",
"출동! 메소레인저 시즌3_2 - Santa_Rocks",
"츄츄 빌리지 - Chew_Chew_Island_Main_Theme",
"침공당한 아쉴롬 - DeathOfAsylumChoir",
"침공당한 크리스탈 아카데미아 - DeathOfAsylum",
"카루파의 마을 - The_Village_of_Karupa",
"카이저 튜토리얼 - Step_of_Kaiser",
"카이저 튜토리얼 - Trapped_Kaiser",
"캐시샵 - Calm_Village",
"커닝 타워 - LoversIntheAfternoon",
"커닝스퀘어 로비 - KerningSquare",
"커닝스퀘어 필드 - KerningSquareField",
"커닝스퀘어행 지하철 내부 - KerningSquareSubway",
"커닝시티 - BadGuys",
"커닝시티 늪지대 - Jungle_Book",
"커닝시티 지하철 - Subway",
"켄타로우스의 영역 - Acient_Forest",
"코-크타운 - CokeTown",
"코디왕 이벤트 - coordiKing",
"콘크리트 로드 - National_Park",
"쿨란 초원 - Finding_Forest",
"퀘스트 중 긴급상황 - Unexpected_Crisis",
"퀘스트중 개그테마 - Life_is_Comedy",
"크리세 필드 - Krease_Field",
"크리스마스 행복한 마을 - WhiteChristmas",
"크리스탈 가든 - Fly_to_the_Moon",
"크리스탈 가든 항해중 - Dancing_with_the_Moon",
"크리스탈 스킬 - 글로리 윙 - gloryWing",
"크리스탈 아카데미아 - CrystalAcademia",
"크리스탈가든 출진 - Black_Heaven_Theme_Parade",
"크리티아스 - Stop_in_Hundreds",
"크리티아스 침공전 - Stop_in_Ends",
"크리티아스 필드 - Tragic_Forest",
"크리티아스 필드 침공전 - Tragic_Restart",
"크림슨우드 성채 - fadedCitadel",
"크세르크세스 - Krease_Colosseum",
"키네시스 테마1 - Kinesis_Theme_I",
"키네시스 테마2 - Kinesis_Theme_II",
"타락한 세계수 - Climbing Up the World Tree",
"타이핑디펜스 - Master_of_Keyboard",
"태국 플로팅 마켓 - Thai_Town",
"태국 플로팅 마켓 필드 - Thai_Field",
"테라숲 - TeraForest",
"트뤼에페 - in_Ruin_in_Vain",
"트뤼에페 광장 - MemoryOfKritias",
"파괴된 헤네시스 - Destruction_Town",
"파왕 우르스 테마 - TheKingOfDestruction",
"파왕 우르스 페이즈1 - The_Silent_War",
"파왕 우르스 페이즈2 - Wild_Fury",
"파왕 우르스 페이즈2(구버전) - Wild_Fury",
"파왕 우르스 페이즈3 - Desperately",
"파파픽시 - Plot_of_Pixie",
"파풀라투스 - Time_Attack",
"판타스틱 테마파크 - FantasticThemePark",
"판타스틱 테마파크 - FantasticThemePark2017",
"판테온 - Pantheon",
"판테온 대신전 - Great_Temple",
"판테온 성소 - Nova_Sanctum",
"판테온 외곽 - Border_Area",
"판테온 필드 - Pantheon_Field",
"패스파인더 - Pathfinder",
"팬텀 튜토리얼 - Injustice",
"팬텀 튜토리얼 영상 - Release Your Spirit High",
"펑고스 숲 - Fungus_Forest",
"펑고스 숲 속 어딘가(퀘스트 중) - Fungus_Forest_B",
"페리온 - Nightmare",
"폐광 - Abandoned_Mine",
"폭군의 성채 - Citadel_of_Tyrant",
"풀 문 파티 - fullmoon_party",
"프란시스 테마 - The_Doll_Master",
"프렌즈 월드 회상 - Memory_of_Sunset",
"프렌즈스토리 락앤롤 주제곡 - Catch_Your_Dreams!",
"프렌즈스토리 오프닝 추출",
"프렌즈스토리 챕터6 엔딩 - Catch_Your_Dreams!_(Vocaless_ver)",
"프로즌 링크 - mapleGalaxy2",
"플래그 레이스 - captureTheFlag",
"플로리나 비치 - Beachway",
"피에르 - Joyful_Tea_Party",
"핑크빈 - Fighting_Pinkbeen",
"하늘 숲,천도 과수원 - Mureung_Forest",
"하늘고래산, 에르밸리 - Chew_Chew_Island_Wild_World",
"하이파이브 업데이트 V코인샵 - VEvent",
"해저 11~14층,33층,48층 - Jungle_in_the_Sea",
"해저 26,27,34층 - Hazard_From_Cave",
"해저 47,49,50층 - Strange_Sort_of_Story",
"행성 비타 미니게임 - GalaxyisDangerous",
"헌티드 멘션 - Haunted_House",
"헤네시스 - FloralLife",
"헤네시스 시장 - Go_Picnic",
"헤네시스 필드1 - Cava_Bien",
"헤네시스 필드2 - Rest_n_Peace",
"헤네시스 필드3 - Blue_Sky",
"헤카톤 - Hekaton",
"헬리시움 도심지 - Helisium_Field",
"헬리시움 암시장 - Funky_Black_Market",
"헬리시움 탈환 본부 - Retake",
"헬리시움 필드 - Helisium_Mystic_Forest",
"현재의 문 - Against_The_Dark",
"혼노지 - Inside_Honnouji",
"혼테일 - Hontale",
"황금사원 - Gold_Temple_Town",
"황룡,적룡파 도장 - Dragon_Tiger_Field",
"황혼의 페리온 - Destruction_Perion_Shelter",
"황혼의 페리온 필드 - Destruction_Perion",
"황혼의 페리온 필드(구버전) - Destruction_Perion",
"회절의 회랑, 보스 윌 페이즈1 - Diffraction",
"회절의 회랑, 보스 윌 페이즈1(구버전) - Diffraction",
"후회의 길 - Repentance",
"히에이잔 - Hieijan",
"힐라 - Red_Witch"


]

selectList_pokemon1 = [

"가디",
"강챙이",
"갸라도스",
"거북왕",
"고라파덕",
"고오스",
"고우스트",
"고지",
"골덕",
"골뱃",
"괴력몬",
"구구",
"근육몬",
"깨비드릴조",
"깨비참",
"꼬렛",
"꼬마돌",
"꼬부기",
"나시",
"나옹",
"나인테일",
"날쌩마",
"냄새꼬",
"니드런♀",
"니드런♂",
"니드리나",
"니드리노",
"니드퀸",
"니드킹",
"닥트리오",
"단데기",
"덩쿠리",
"데구리",
"도나리",
"독침붕",
"독파리",
"두두",
"두트리오",
"디그다",
"딱구리",
"딱충이",
"또가스",
"또도가스",
"뚜벅쵸",
"라이츄",
"라프라스",
"라플레시아",
"럭키",
"레어코일",
"레트라",
"롱스톤",
"루주라",
"리자드",
"리자몽",
"마그마",
"마임맨",
"망나뇽",
"망키",
"메타몽",
"모다피",
"모래두지",
"뮤",
"뮤츠",
"미뇽",
"발챙이",
"버터플",
"별가사리",
"부스터",
"붐볼",
"뿔충이",
"뿔카노",
"쁘사이저",
"삐삐",
"샤미드",
"성원숭",
"셀러",
"슈륙챙이",
"스라크",
"슬리퍼",
"슬리프",
"시드라",
"시라소몬",
"식스테일",
"신뇽",
"썬더",
"쏘드라",
"아라리",
"아보",
"아보크",
"아쿠스타",
"알통몬",
"암나이트",
"암스타",
"야도란",
"야돈",
"어니부기",
"에레브",
"왕눈해",
"왕콘치",
"우츠동",
"우츠보트",
"윈디",
"윤겔라",
"이브이",
"이상해꽃",
"이상해씨",
"이상해풀",
"잉어킹",
"잠만보",
"주뱃",
"쥬레곤",
"쥬쥬",
"쥬피썬더",
"질뻐기",
"질퍽이",
"찌리리공",
"캐이시",
"캐터피",
"캥카",
"켄타로스",
"코뿌리",
"코일",
"콘치",
"콘팡",
"크랩",
"킹크랩",
"탕구리",
"텅구리",
"투구",
"투구푸스",
"파라섹트",
"파라스",
"파르셀",
"파오리",
"파이리",
"파이어",
"팬텀",
"페르시온",
"포니타",
"폴리곤",
"푸린",
"푸크린",
"프리져",
"프테라",
"피죤",
"피죤투",
"피카츄",
"픽시",
"홍수몬",
"후딘"


]